#!/bin/bash

file=$(basename $1)
editor=code

generate_name() {
    pckname=$1
    arr=(${pckname//-/ })
    name_elements=$(expr ${#arr[@]} - 2)
    name=${arr[0]}

    for i in $(seq 1 $name_elements);
    do
        name="$name-${arr[$i]}"
    done

    echo $name
}

pckname_wver=${file%.t*}
pckname=$(generate_name $pckname_wver)
version="${pckname_wver##*-}"

pckdir=${pckname:0:1}/$pckname

mkdir -p packages/$pckdir/files

cp modules/bin-releases/$file packages/$pckdir/files/

echo "./configure --prefix=/usr" > packages/$pckdir/build.sh
echo "make" >> packages/$pckdir/build.sh
echo 'make DESTDIR=$PCKDIR install' >> packages/$pckdir/build.sh

echo "name=$pckname" > packages/$pckdir/pck
echo "version=$version" >> packages/$pckdir/pck
echo "source=$file" >> packages/$pckdir/pck

if [ "$2" == "-i" ]; then
	mkdir -p packages/$pckdir/install
	touch packages/$pckdir/install/install.sh
fi

$editor packages/$pckdir/build.sh

