#!/bin/bash

file=$(basename $1)
editor=code

generate_name() {
    pckname=$1
    arr=(${pckname//-/ })
    name_elements=$(expr ${#arr[@]} - 2)
    name=${arr[0]}

    for i in $(seq 1 $name_elements);
    do
        name="$name-${arr[$i]}"
    done

    echo $name
}

pckname_wver=${file%.t*}
pckname=$(generate_name $pckname_wver)
version="${pckname_wver##*-}"

mkinstall="no"

if [ "$2" == "-i" ]; then
	mkinstall="yes"
elif [ "$2" != "" ]; then
        pckname=$2

	if [ "$3" == "-i" ]; then
		mkinstall="yes"
	fi
fi

pckdir=${pckname:0:1}/$pckname

mkdir -p packages/$pckdir/files

cp modules/bin-releases/$file packages/$pckdir/files/

echo "mkdir __build && cd __build" > packages/$pckdir/build.sh
echo "meson setup --prefix=/usr --buildtype=release .." >> packages/$pckdir/build.sh
echo "ninja" >> packages/$pckdir/build.sh
echo 'DESTDIR=$PCKDIR ninja install' >> packages/$pckdir/build.sh

if [ "$mkinstall" == "yes" ]; then
        mkdir -p packages/$pckdir/install
        touch packages/$pckdir/install/install.sh
fi

echo "name=$pckname" > packages/$pckdir/pck
echo "version=$version" >> packages/$pckdir/pck
echo "source=$file" >> packages/$pckdir/pck

$editor packages/$pckdir/build.sh

